from typing import Protocol, Tuple, List


class ISocialService(Protocol):
    # Likes
    async def toggle_like(self, user_id: str, article_id: str, add: bool) -> bool: ...
    async def check_liked(self, user_id: str, article_id: str) -> bool: ...
    async def get_like_stats(self, article_id: str) -> dict: ...

    # Bookmarks
    async def toggle_bookmark(
        self, user_id: str, article_id: str, add: bool
    ) -> bool: ...
    async def check_bookmarked(self, user_id: str, article_id: str) -> bool: ...
    async def get_bookmarks(
        self, user_id: str, page: int, limit: int
    ) -> Tuple[List, int]: ...

    # Follows
    async def toggle_follow(
        self, follower_id: str, following_id: str, add: bool
    ) -> bool: ...
    async def check_following(self, follower_id: str, following_id: str) -> bool: ...
    async def list_followers(
        self, user_id: str, page: int, limit: int
    ) -> Tuple[List, int]: ...
    async def list_following(
        self, user_id: str, page: int, limit: int
    ) -> Tuple[List, int]: ...

    # Stats
    async def get_user_social_stats(self, user_id: str) -> dict: ...
