INSERT_ARTICLE_EVENT = (
    "INSERT INTO article_events"
    " (id, article_id, actor_user_id, event_type, event_value, event_source, metadata_json)"
    " VALUES (?, ?, NULLIF(?, ''), ?, ?, ?, NULLIF(?, ''))"
)

UPSERT_HOURLY_SUCCESS = (
    "INSERT INTO article_success_hourly"
    " (article_id, bucket_hour, views_count, likes_count, comments_count, outcome_events_count,"
    "  outcome_tag_count, engagement_score, success_rate, updated_at)"
    " SELECT"
    "   e.article_id,"
    "   ?,"
    "   SUM(CASE WHEN e.event_type = 'VIEW' THEN e.event_value ELSE 0 END) AS views_count,"
    "   SUM(CASE WHEN e.event_type = 'LIKE' THEN e.event_value ELSE 0 END) AS likes_count,"
    "   SUM(CASE WHEN e.event_type = 'COMMENT' THEN e.event_value ELSE 0 END) AS comments_count,"
    "   SUM(CASE WHEN e.event_type = 'OUTCOME' THEN e.event_value ELSE 0 END) AS outcome_events_count,"
    "   COALESCE(ot.outcome_tag_count, 0) AS outcome_tag_count,"
    "   ROUND((SUM(CASE WHEN e.event_type = 'VIEW' THEN e.event_value ELSE 0 END) * 1.0)"
    "     + (SUM(CASE WHEN e.event_type = 'LIKE' THEN e.event_value ELSE 0 END) * 5.0)"
    "     + (SUM(CASE WHEN e.event_type = 'COMMENT' THEN e.event_value ELSE 0 END) * 8.0)"
    "     + (SUM(CASE WHEN e.event_type = 'OUTCOME' THEN e.event_value ELSE 0 END) * 10.0)"
    "     + (COALESCE(ot.outcome_tag_count, 0) * 4.0), 2) AS engagement_score,"
    "   MIN(100.0, ROUND((("
    "     (SUM(CASE WHEN e.event_type = 'VIEW' THEN e.event_value ELSE 0 END) * 1.0)"
    "     + (SUM(CASE WHEN e.event_type = 'LIKE' THEN e.event_value ELSE 0 END) * 5.0)"
    "     + (SUM(CASE WHEN e.event_type = 'COMMENT' THEN e.event_value ELSE 0 END) * 8.0)"
    "     + (SUM(CASE WHEN e.event_type = 'OUTCOME' THEN e.event_value ELSE 0 END) * 10.0)"
    "     + (COALESCE(ot.outcome_tag_count, 0) * 4.0)"
    "   ) / 200.0) * 100.0, 2)) AS success_rate,"
    "   datetime('now')"
    " FROM article_events e"
    " LEFT JOIN ("
    "   SELECT at.article_id, COUNT(*) AS outcome_tag_count"
    "   FROM article_tags at"
    "   JOIN tags t ON t.id = at.tag_id"
    "   WHERE t.tag_type = 'outcome'"
    "   GROUP BY at.article_id"
    " ) ot ON ot.article_id = e.article_id"
    " WHERE e.created_at >= ? AND e.created_at < ?"
    " GROUP BY e.article_id"
    " ON CONFLICT(article_id, bucket_hour) DO UPDATE SET"
    "   views_count = excluded.views_count,"
    "   likes_count = excluded.likes_count,"
    "   comments_count = excluded.comments_count,"
    "   outcome_events_count = excluded.outcome_events_count,"
    "   outcome_tag_count = excluded.outcome_tag_count,"
    "   engagement_score = excluded.engagement_score,"
    "   success_rate = excluded.success_rate,"
    "   updated_at = datetime('now')"
)

COUNT_EVENTS_IN_WINDOW = (
    "SELECT COUNT(*) AS count"
    " FROM article_events"
    " WHERE created_at >= ? AND created_at < ?"
)
