from typing import Optional, Protocol


class IFeedService(Protocol):
    async def home(self, page: int, user_id: Optional[str], topics: list) -> dict: ...
    async def featured(self) -> list: ...
    async def following(self, user_id: str, page: int) -> dict: ...
