repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '^node_modules/'
      - id: ruff-format
        exclude: '^node_modules/'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^node_modules/'
      - id: end-of-file-fixer
        exclude: '^node_modules/'
      - id: detect-private-key
        exclude: '^node_modules/'
