from typing import Optional, Protocol
from models.tag.model import Tag


class ITagService(Protocol):
    async def list_all(self) -> list: ...
    async def get_by_slug_or_id(self, identifier: str) -> Optional[Tag]: ...
    async def create(self, name: str) -> Tag: ...
