from typing import Optional, Protocol
from models.user.model import User


class IUserService(Protocol):
    async def get_by_id(self, user_id: str, scope: str) -> Optional[User]: ...
    async def update_profile(
        self, user_id: str, name: str, avatar_url: Optional[str]
    ) -> None: ...
    async def self_upgrade_to_author(self, user_id: str) -> None: ...
    async def set_role(self, user_id: str, role: str) -> None: ...
    async def get_prefs(self, user_id: str) -> dict: ...
    async def update_prefs(
        self, user_id: str, topics: list, email_notifs: int, theme: str
    ) -> None: ...
