from typing import Protocol


class IAdminService(Protocol):
    async def get_stats(self) -> dict: ...
    async def get_approval_queue(self, page: int) -> dict: ...
    async def list_users(self, page: int) -> dict: ...
    async def ban_user(self, user_id: str) -> None: ...
    async def unban_user(self, user_id: str) -> None: ...
    async def get_notifications(self, user_id: str, page: int) -> dict: ...
    async def mark_notifications_read(self, user_id: str) -> None: ...
