class UserRole:
    SUPERADMIN = "SUPERADMIN"
    APPROVER = "APPROVER"
    AUTHOR = "AUTHOR"
    READER = "READER"
    ALL = (SUPERADMIN, APPROVER, AUTHOR, READER)
    CAN_WRITE = (SUPERADMIN, APPROVER, AUTHOR)
    CAN_APPROVE = (SUPERADMIN, APPROVER)


class ArticleStatus:
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"
    EDITABLE = (DRAFT, REJECTED)
    ALL = (DRAFT, SUBMITTED, APPROVED, REJECTED, PUBLISHED, ARCHIVED)


class ArticleContentType:
    ARTICLE = "article"
    HOW_TO = "how-to"
    CASE_STUDY = "case-study"
    RESEARCH = "research"
    ALL = (ARTICLE, HOW_TO, CASE_STUDY, RESEARCH)


class NotificationType:
    LIKE = "LIKE"
    COMMENT = "COMMENT"
    FOLLOW = "FOLLOW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
    MODERATION_PENDING = "MODERATION_PENDING"
    MODERATION_REJECTED = "MODERATION_REJECTED"
    FEATURE_ANNOUNCEMENT = "FEATURE_ANNOUNCEMENT"
    ALL = (
        LIKE,
        COMMENT,
        FOLLOW,
        APPROVED,
        REJECTED,
        PUBLISHED,
        MODERATION_PENDING,
        MODERATION_REJECTED,
        FEATURE_ANNOUNCEMENT,
    )


class Scope:
    PUBLIC = "public"
    PRIVATE = "private"
    LIST = "list"
    DETAIL = "detail"
    ADMIN = "admin"
