class UserRole:
    SUPERADMIN = "SUPERADMIN"
    APPROVER = "APPROVER"
    AUTHOR = "AUTHOR"
    READER = "READER"
    ALL = (SUPERADMIN, APPROVER, AUTHOR, READER)
    CAN_WRITE = (SUPERADMIN, APPROVER, AUTHOR)
    CAN_APPROVE = (SUPERADMIN, APPROVER)


class ArticleStatus:
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"
    EDITABLE = (DRAFT, REJECTED)
    ALL = (DRAFT, SUBMITTED, APPROVED, REJECTED, PUBLISHED, ARCHIVED)


class NotificationType:
    LIKE = "LIKE"
    COMMENT = "COMMENT"
    FOLLOW = "FOLLOW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
    ALL = (LIKE, COMMENT, FOLLOW, APPROVED, REJECTED, PUBLISHED)


class Scope:
    PUBLIC = "public"
    PRIVATE = "private"
    LIST = "list"
    DETAIL = "detail"
    ADMIN = "admin"
