from typing import Optional, Protocol, Tuple
from models.comment.model import Comment


class ICommentService(Protocol):
    async def get_by_id(self, comment_id: str) -> Optional[Comment]: ...
    async def list_for_article(
        self, article_id: str, page: int, limit: int
    ) -> list: ...
    async def list_for_article_with_replies(
        self, article_id: str, page: int, limit: int
    ) -> Tuple[list, int]: ...
    async def list_replies(
        self, parent_id: str, page: int, limit: int
    ) -> Tuple[list, int]: ...
    async def list_all_for_moderation(
        self, page: int, limit: int
    ) -> Tuple[list, int]: ...
    async def create(self, req, author_id: str) -> str: ...
    async def update(self, comment_id: str, req, requesting_user_id: str) -> None: ...
    async def delete(
        self, comment_id: str, requesting_user_id: str, is_superadmin: bool
    ) -> None: ...
    async def flag_spam(self, comment_id: str, user_id: str) -> None: ...
    async def moderate(self, comment_id: str, req, moderator_id: str) -> None: ...
